### ISSUE TITLE
"clear" command is ambiguous when the mark is a single digit

### ISSUE THREAD

**Issue by seabadger** [cursorless-dev/cursorless-talon#154]
There seems to be a collision between the cursorless “clear” command and the “clear [line] <number>” command in knausj_talon/text/line_commands.talon. 
E.g., ff there's a hat  above a number (say, a 3), and I say “clear three”, intending to delete the character “3" under a hat and place the cursor there, instead line 3 gets deleted.

I don't hit this one too often but it is pretty...surprising... when it happens.

**Comment by AndreasArvidsson** [comment]
Sadly there is no way as far as I know to fix this conflict while keeping the commands as they are. The default spoken form in cursorless is now "change" for this very reason. Either you have to change the spoken form in cursorless or in knausj.

**Comment by AndreasArvidsson** [comment]
The current cursorless issue regarding these conflicts is here
https://github.com/cursorless-dev/cursorless-vscode/issues/428

**Comment by seabadger** [comment]
> The default spoken form in cursorless is now "change" for this very reason.
Is this user visible?  For me change does not work but clear does.   the cheat sheet  only shows clear as well.

**Comment by AndreasArvidsson** [comment]
That default spoken form is only used for new installation since we don't retroactively update the users spoken commands. These are lock down in your csv files. If you want to update the spoken form look into `cursorless-settings/actions.csv`

**Comment by pokey** [comment]
We keep users' existing spoken forms on update because we figure it is not great ux if your spoken forms just change out from under you

Maybe we should pop something up to indicate that the default has changed and to ask if you want to migrate to the new default?

**Comment by seabadger** [comment]
That could be a good thing, but might be easy to miss/inadvertently
dismiss. Maybe it could be complemented by a high-level changelog
summarizing these kinds of changes? (changes to spoken forms, new
commands/marks/etc being added, that kind of thing?)
