### ISSUE TITLE
`bring` and indentation

### ISSUE THREAD

**Issue by ym-han** [cursorless-dev/cursorless-talon#155]
Apologies if this has been brought up already, or if there's a simple solution for it. I'm finding that `bring` doesn't always get the indentation right. E.g., bringing the if block from lines 45 to 50 to line 41 in 

![image](https://user-images.githubusercontent.com/21286812/155069627-b8dba3b8-ca6d-4bd4-aa99-bb6f5fe31104.png)

results in the indentation in most of the pasted if block being wonky:

![image](https://user-images.githubusercontent.com/21286812/155069862-b806397d-a87a-440e-acca-e820218adee9.png)

**Comment by pokey** [comment]
I believe this is covered by https://github.com/cursorless-dev/cursorless-vscode/issues/302. @AndreasArvidsson agreed?

**Comment by AndreasArvidsson** [comment]
Yes I think so too. Won't help languages like python that much but above example should work.
